# Generated by Django 4.0.1 on 2022-02-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='catergory',
            field=models.TextField(default='add catergory'),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
