# Generated by Django 4.0.1 on 2022-02-12 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsstory_catergory_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='catergory',
        ),
    ]
