# Generated by Django 4.0.1 on 2022-02-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_newsstory_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='colors',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.URLField(default='https://stickershop.line-scdn.net/stickershop/v1/product/3710576/LINEStorePC/main.png;compress=true'),
        ),
    ]
