# Generated by Django 4.0.1 on 2022-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsstory_colors_alter_newsstory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='colors',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='catergory',
            field=models.CharField(choices=[('cat', 'CAT'), ('dog', 'DOG'), ('horse', 'HORSE'), ('duck', 'DUCK'), ('other', 'OTHER')], default='select', max_length=6),
        ),
    ]
